// src/App.vue
<script setup lang="ts">
import {onMounted, onUnmounted, ref, watchEffect} from "vue";
import {invoke} from "@tauri-apps/api/core";
import {Button} from "@/components/ui/button";
import {CircleCheckBig, Loader} from 'lucide-vue-next';
import {getCurrentWebview} from "@tauri-apps/api/webview";

import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import {open} from '@tauri-apps/plugin-dialog';
import {readFile} from '@tauri-apps/plugin-fs';
import {convertBytes} from "./lib/utils.ts";
import {UnlistenFn} from "@tauri-apps/api/event";

// 压缩文件对象
interface ImageFile {
  raw_path: string;
  savePath: string;
  file_name: string;
  size: number;
  compressedSize: number;
}

interface CompressedFile {
  saved_path: string;
  size: number;
}


const files = ref<ImageFile[]>([]);

async function selectFileHandle() {
  files.value = []
  const selected = await open({
    multiple: true,
    filters: [
      {
        name: "Images",
        extensions: ["png", "jpg", "jpeg"],
      },
    ],
  });
  if (Array.isArray(selected)) {
    // user selected multiple files
    for (let file of selected) {
      const fileData = await readFile(file);
      files.value.push({
        file_name: file.split('/').pop() || "",
        raw_path: file,
        size: fileData.length,
        compressedSize: 0,
        savePath: "",
      })
    }

    console.log(selected)
  } else if (selected === null) {
    // user
  }
}

watchEffect(async () => {
  console.log("加班了")
  for (let file of files.value) {
    let compress_file: CompressedFile = await invoke('compress_image', {filePath: file.raw_path})
    file.compressedSize = compress_file.size;
    file.savePath = compress_file.saved_path;
  }
})

async function openHandle(p: String) {
  if (p === "") {
    console.log("not path")
    return
  }
  await invoke('open_folder', {path: p})
}

let unlisten: UnlistenFn | null = null;
onMounted(async () => {
  unlisten = await getCurrentWebview().onDragDropEvent((event) => {
    if (event.payload.type === 'drop') {
      console.log('User dropped', event.payload.paths);
      for (let file of event.payload.paths) {
        readFile(file).then((fileData) => {
          files.value.push({
            file_name: file.split('/').pop() || "",
            raw_path: file,
            size: fileData.length,
            compressedSize: 0,
            savePath: "",
          })
        });
      }
    }
  });
})

onUnmounted(()=>{
  if (unlisten !== null) unlisten()
})

</script>

<template>
  <main class="container">
    <h1 class="text-2xl text-center mb-4">Image to Tiny</h1>
    <div class="flex flex-col gap-2 items-center justify-center py-12 rounded-3xl border-dashed border-2"
         v-if="files.length === 0">
      <div class="text-xl">Drag and drop image files</div>
      <div class="text-base text-gray-400 mb-8">Supports the following formats:png, jpg, jpeg</div>
      <Button variant="outline" class="w-24" @click="selectFileHandle">Select files</Button>
    </div>
    <div v-else>
      <div class="flex flex-wrap items-center justify-between gap-4 mt-4">
        <h1 class="flex-1">All files</h1>
        <Button variant="outline" class="w-24" @click="selectFileHandle">Select files</Button>
      </div>
      <Table>
        <TableCaption>
          The output image is in the output directory at the original image location.
        </TableCaption>
        <TableHeader>
          <TableRow>
            <TableHead class="w-[200px]">
              File
            </TableHead>
            <TableHead>Before Size</TableHead>
            <TableHead>After Size</TableHead>
            <TableHead>Status</TableHead>
            <TableHead class="text-right">
              Saved up
            </TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          <TableRow v-for="(file,i) in files" :key="i">
            <TableCell class="font-medium">
              <a class="underline" href="javascript:;" @click="openHandle(file.savePath)">{{ file.file_name }}</a>
            </TableCell>
            <TableCell>
              <span>{{ convertBytes(file.size) }} </span>
            </TableCell>
            <TableCell>
              <span class="text-green-600" v-if="file.compressedSize > 0">{{ convertBytes(file.compressedSize) }}</span>
            </TableCell>
            <TableCell class="text-right">
              <CircleCheckBig class="text-green-400 w-4 h-4" v-if="file.compressedSize > 0"/>
              <Loader class="animate-spin w-4 h-4 " v-else/>
            </TableCell>
            <TableCell class="text-right">
              {{ file.compressedSize ? `${((file.size - file.compressedSize) / file.size * 100).toFixed(2)}%` : "0%" }}
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </div>
  </main>
</template>

// app/page.tsx
"use client";

import {
  Button,
  Chip,
  getKeyValue,
  Table,
  TableBody,
  TableCell,
  TableColumn,
  TableHeader,
  TableRow,
} from "@heroui/react";
import { readFile } from "@tauri-apps/plugin-fs";
import { useEffect, useReducer, useState } from "react";
import { compressedReducer, ImageFile } from "@/app/reducer";
import { open, save } from "@tauri-apps/plugin-dialog";
import React from "react";
import { LoaderPinwheel, SendHorizontal, TicketX } from "lucide-react";
import { convertBytes } from "./utils";
import { invoke } from "@tauri-apps/api/core";
import { getCurrentWebview } from "@tauri-apps/api/webview";
import { ChooseFile } from "@/components/chooseFile";

interface CompressedFile {
  saved_path: string;
  size: number;
}

const statusColorMap = {
  ready: "default",
  compressing: "primary",
  error: "danger",
  compressed: "success",
};

export default function Home() {
  const [files, dispatch] = useReducer(compressedReducer, []);
  const [compressLoading, setCompressLoading] = useState(false);
  const [savePath, setSavePath] = useState("");

  async function selectFileHandle() {
    const selected = await open({
      multiple: true,
      filters: [
        {
          name: "Images",
          extensions: ["png", "jpg", "jpeg"],
        },
      ],
    });
    if (Array.isArray(selected)) {
      // user selected multiple files
      for (let file of selected) {
        const fileData = await readFile(file);

        dispatch({
          type: "added",
          payload: {
            file_name: file.split("/").pop() || "",
            raw_path: file,
            size: fileData.length,
            compressedSize: 0,
            savePath: "",
            status: "ready",
          },
        });
      }
    } else if (selected === null) {
      // user
    }
  }

  useEffect(() => {
    getCurrentWebview().onDragDropEvent((event) => {
      if (event.payload.type === "enter") {
        // 清空 files
        dispatch({
          type: "clear",
          payload: {
            file_name: "",
            raw_path: "",
            size: 0,
            compressedSize: 0,
            savePath: "",
            status: "ready",
          },
        });
      }
      if (event.payload.type === "drop") {
        for (let file of event.payload.paths) {
          readFile(file).then((fileData) => {
            dispatch({
              type: "added",
              payload: {
                file_name: file.split("/").pop() || "",
                raw_path: file,
                size: fileData.length,
                compressedSize: 0,
                savePath: "",
                status: "ready",
              },
            });
          });
        }
      }
    });
  }, []);

  async function selectSavePathHandle() {
    const path = await open({
      directory: true,
      multiple: false,
    });

    if (path === null) {
      return;
    }

    setSavePath(path);
  }
  async function compressFileHandle() {
    setCompressLoading(true);

    for (let file of files) {
      if (file.status === "compressed") {
        continue;
      }
      try {
        let compress_file: CompressedFile = await invoke("compress_image", {
          filePath: file.raw_path,
          saveDir: savePath,
        });
        file.compressedSize = compress_file.size;
        file.savePath = compress_file.saved_path;
        file.status = "compressed";
        dispatch({
          type: "changed",
          payload: file,
        });
      } catch (e: any) {
        file.status = "error";
        dispatch({
          type: "changed",
          payload: file,
        });
      }
    }
    setCompressLoading(false);
  }

  const renderCell = React.useCallback((file: ImageFile, columnKey: any) => {
    const cellValue = getKeyValue(file, columnKey);
    const statusColor = (statusColorMap[file.status] ?? "default") as
      | "default"
      | "primary"
      | "danger"
      | "success"
      | "secondary"
      | "warning"
      | undefined;
    switch (columnKey) {
      case "status":
        return (
          <Chip
            className="capitalize"
            color={statusColor}
            size="sm"
            variant="flat"
          >
            {cellValue}
          </Chip>
        );
      case "compressedSize":
        return convertBytes(cellValue);
      case "size":
        return convertBytes(cellValue);
      case "saveup":
        return file.compressedSize
          ? `${(((file.size - file.compressedSize) / file.size) * 100).toFixed(2)}%`
          : "-";
      default:
        return cellValue;
    }
  }, []);

  return (
    <div className="h-full relative">
      {files.length > 0 ? (
        <div className="h-full">
          <div className="flex gap-2 items-center mb-2">
            {/* <div className="flex-1"></div> */}
            <Button
              size="sm"
              className="flex-1 text-left flex items-center justify-start"
              onPress={selectSavePathHandle}
            >
              <span>
                {savePath
                  ? `Save path: ${savePath}`
                  : "Please select save path"}
              </span>
            </Button>

            <Button
              size="sm"
              color="primary"
              className="shadow-2xl "
              onPress={compressFileHandle}
              disabled={compressLoading}
            >
              {compressLoading ? (
                <LoaderPinwheel className="w-5 h-5 animate-spin" />
              ) : (
                <SendHorizontal className="w-5 h-5" />
              )}
              <span>Go!</span>
            </Button>
            <Button
              size="sm"
              className="shadow-2xl "
              onPress={() => {
                dispatch({
                  type: "clear",
                  payload: {
                    file_name: "",
                    raw_path: "",
                    size: 0,
                    compressedSize: 0,
                    savePath: "",
                    status: "ready",
                  },
                });
              }}
            >
              <TicketX className="w-5 h-5" />
              <span>Clear</span>
            </Button>
          </div>
          <Table aria-label="Files">
            <TableHeader>
              <TableColumn key={"file_name"}>File({files.length})</TableColumn>
              <TableColumn width={"100"} key={"size"}>
                Before Size
              </TableColumn>
              <TableColumn width={"120"} key={"compressedSize"}>
                Final Size
              </TableColumn>
              <TableColumn width={"120"} key={"status"}>
                Status
              </TableColumn>
              <TableColumn width={"80"} key={"saveup"}>
                Save Up
              </TableColumn>
            </TableHeader>
            <TableBody>
              {files.map((file: ImageFile) => (
                <TableRow key={file.file_name}>
                  {(columnKey) => (
                    <TableCell>{renderCell(file, columnKey)}</TableCell>
                  )}
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      ) : (
        <div className="h-full pb-4 px-4">
          <div className="h-full mt-2 p-14 bg-zinc-300/20 rounded-xl">
            <ChooseFile onSelectFile={selectFileHandle} />
          </div>
        </div>
      )}
    </div>
  );
}
