// app/settings/page.tsx
"use client";

import { NumberInput } from "@heroui/react";
import { Store } from "@tauri-apps/plugin-store";
import { useEffect, useLayoutEffect, useRef, useState } from "react";

interface SettingsInterface {
  quality: number;
}

export default function DocsPage() {
  const [settings, setSettings] = useState<SettingsInterface>({
    quality: 100,
  });
  const storeRef = useRef<Store | undefined>(undefined);

  useEffect(() => {
    let isMounted = true;
    let fn = async () => {
      const store = await Store.load("settings.json");
      storeRef.current = store;
      const storedSettings = await store.get<SettingsInterface>("settings");
      if (isMounted && storedSettings) {
        console.log("storedSettings", storedSettings);
        setSettings({
          ...storedSettings,
        });
      }
    };
    fn();
    return () => {
      isMounted = false;
    };
  }, []);

  useLayoutEffect(() => {
    const store = storeRef.current;
    if (store) {
      console.log("保存设置:", settings);
      store.set("settings", settings);
      store.save();
    }
  }, [settings]);

  // set quality
  async function handleQualityChange(value: number) {
    if (storeRef.current) {
      setSettings({
        ...settings,
        quality: value,
      });
      console.log("settings", settings);
    }
  }

  return (
    <div className="h-full w-full mt-2 p-4 bg-zinc-300/20 rounded-xl">
      <h2 className="text-3xl mb-4">settings</h2>
      <div className="mb-4 flex items-start justify-between gap-2">
        <div className="text-zinc-600/70 dark:text-zinc-200/70">
          <h2 className="text-lg">Compressed image quality</h2>
          <span className="text-sm text-zinc-600/40 dark:text-zinc-200/40">The smaller the value, the smaller the image capacity, but the lower the image quality.</span>
        </div>
        <NumberInput
          className="max-w-3xs"
          label="Quality"
          defaultValue={100}
          value={settings.quality}
          step={5}
          max={100}
          min={70}
          onValueChange={(v) => handleQualityChange(v)}
        />
      </div>
    </div>
  );
}

// src/pages/settings.vue
<script setup lang="ts">
import {Input} from '@/components/ui/input'
import {Button} from "@/components/ui/button";
import {Separator} from '@/components/ui/separator'
import {Slider} from '@/components/ui/slider'
import {Store} from '@tauri-apps/plugin-store';

import {ref, onMounted} from "vue";

interface SettingsInterface {
  quality: number[];
  imageCompressSavePath: string;
  imageConvertSavePath: string;
}

const form = ref<SettingsInterface>({
  quality: [80],
  imageCompressSavePath: "",
  imageConvertSavePath: "",
})

let store: Store;

onMounted(async () => {
  store = await Store.load('settings.json')
  const store_form = await store.get<SettingsInterface>('settings');
  if (store_form) {
    form.value = store_form
  }
})


async function handleVolumeChange() {
  console.log("set quality")
  await store.set('settings', form.value)
  await store.save()
}

</script>

<template>
  <main class="container h-full flex flex-col justify-start items-center">
    <div class="flex items-center flex-row justify-between mb-4 px-6 w-full">
      <h1 class="text-4xl text-left font-bold flex-1 w-full">Settings</h1>
    </div>
    <div class="bg-white py-4 h-full w-full px-4 rounded-2xl">
      <div class="my-4">
        <h2 class="text-zinc-700 text-xl mb-4 capitalize">image compression quality</h2>
        <div class="flex w-full flex-col  items-center gap-1.5">
          <Slider
              v-model="form.quality"
              :max="100"
              :min="20"
              :step="1"
              @valueCommit="handleVolumeChange"
              class="w-full"
          />
          <div class="flex text-left w-full items-center gap-2 justify-between text-zinc-500 text-base">
            <span class="text-xs">Note: Too low quality will lead to image distortion.</span>
            <span>{{ form.quality[0] }}%</span>
          </div>
        </div>
      </div>
      <div class="my-4">
        <h2 class="text-zinc-700 text-xl mb-4">Image compression output directory</h2>
        <div class="text-zinc-400 text-xs mb-2">
          <p>If it is empty, it will be output to the output folder in the directory where the selected picture is located by default.</p>
          <p>For example, for the image compression function, when the image path you select is `/Users/xxx/Downloads/xxx.jpg`, after compression, it is output by default to `/Users/xxx/Downloads/output/xxx.jpg`.</p>
        </div>
        <div class="flex w-full max-w-sm items-center gap-1.5">
          <Input id="imageCompressSavePath" v-model="form.imageCompressSavePath" type="text"/>
          <Button type="submit">
            Select Folder
          </Button>
        </div>
      </div>

      <Separator/>
      <div class="my-4">
        <h2 class="text-zinc-700 text-xl mb-4">Image conversion output directory</h2>
        <div class="text-zinc-400 text-xs mb-2">
          <p>If it is empty, it will be output to the output folder in the directory where the selected picture is located by default.</p>
          <p>For example, if the picture path you select is `/Users/xxx/Downloads/xxx.jpg`, after conversion to PNG, it is output by default to `/Users/xxx/Downloads/output/xxx.png`.</p>
        </div>
        <div class="flex w-full max-w-sm items-center gap-1.5">
          <Input id="imageConvertSavePath" type="text"/>
          <Button type="submit">
            Select Folder
          </Button>
        </div>
      </div>
    </div>
  </main>
</template>

<style scoped>

</style>
