// src/pages/converter.vue
<script setup lang="ts">
import {computed, onMounted, onUnmounted, ref,watchEffect} from "vue";
import {invoke} from "@tauri-apps/api/core";
import {Button} from "@/components/ui/button";
import {CircleX, ImageUp, Send, LoaderCircle} from 'lucide-vue-next';
import {getCurrentWebview} from "@tauri-apps/api/webview";
import {open} from '@tauri-apps/plugin-dialog';
import {UnlistenFn} from "@tauri-apps/api/event";
import { toast } from 'vue-sonner'
import { Toaster } from '@/components/ui/sonner'
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'

// 压缩文件对象
interface ImageFile {
  raw_path: string;
  savePath: string;
  file_name: string;
  to_format: string;
  status: string;
}

interface ConverterResponse {
  status: string;
  save_path: string;
}

const all_to_format = ref("")


const files = ref<ImageFile[]>([]);

async function selectFileHandle() {
  files.value = []
  const selected = await open({
    multiple: true,
    filters: [
      {
        name: "Images",
        extensions: ["png", "jpg", "jpeg", "webp"],
      },
    ],
  });
  if (Array.isArray(selected)) {
    // user selected multiple files
    for (let file of selected) {
      files.value.push({
        file_name: file.split('/').pop() || "",
        raw_path: file,
        to_format: "",
        savePath: "",
        status: "",
      })
    }

    console.log(selected)
  } else if (selected === null) {
    // user
  }
}

watchEffect(() => {
  console.log("console")
  for (let file of files.value) {
    file.to_format = all_to_format.value
  }
})

async function openHandle(p: String) {
  if (p === "") {
    console.log("not path")
    return
  }
  await invoke('open_folder', {path: p})
}

let unlisten: UnlistenFn | null = null;
onMounted(async () => {
  unlisten = await getCurrentWebview().onDragDropEvent((event) => {
    if (event.payload.type === 'drop') {
      console.log('User dropped', event.payload.paths);
      for (let file of event.payload.paths) {
        files.value.push({
          file_name: file.split('/').pop() || "",
          raw_path: file,
          savePath: "",
          to_format: "",
          status: "",
        })
      }
    }
  });
})

onUnmounted(() => {
  if (unlisten !== null) unlisten()
})

// 查看是否所有的文件都设置了转换格式
const allFilesSet = computed(() => {
  return files.value.every(value => value.to_format.length > 0)
});

async function handleRemoveItem(i: number) {
  files.value.splice(i, 1)
}

const loading = ref(false)

async function handleConvert() {
  loading.value = true
  for (let file of files.value) {
    try {
      if (!file.to_format) {
        throw new Error("Please select a format")
      }
      file.status = "In Progress"
      let resp: ConverterResponse = await invoke('convert', {filePath: file.raw_path, toFormat: file.to_format})
      file.status = resp.status;
      file.savePath = resp.save_path;
    } catch (e) {
      file.status = "Error"
    } finally {
      loading.value = false
    }
  }
  toast.info('Finish!')
}

</script>

<template>
  <main class="container h-full flex flex-col justify-start items-center">
    <div class="flex items-center flex-row justify-between mb-4 px-6 w-full">
      <h1 class="text-2xl text-left font-bold flex-1 w-full">Image Converter</h1>
      <div class="flex items-center justify-center mr-4" v-if="files.length>0">
        <span class="capitalize mr-2 text-sm">All Convert to</span>
        <Select v-model="all_to_format">
          <SelectTrigger class="w-[80px] py-0">
            <SelectValue placeholder="..."/>
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              <SelectItem value="jpeg">
                JPEG
              </SelectItem>
              <SelectItem value="png">
                PNG
              </SelectItem>
              <SelectItem value="webp">
                WEBP
              </SelectItem>
            </SelectGroup>
          </SelectContent>
        </Select>
      </div>
      <Button v-if="files.length>0" variant="outline" class="w-24" @click="selectFileHandle">Select files</Button>
    </div>
    <Toaster position="bottom-center" />
    <div class="bg-white rounded-3xl p-6 w-full flex-1">
      <div
          class="flex flex-col gap-2  items-center justify-center py-12 h-full rounded-3xl border-dashed border-2 cursor-pointer"
          v-if="files.length === 0" @click="selectFileHandle">
        <div>
          <ImageUp class="w-12 h-12 text-zinc-600"/>
        </div>
        <div class="text-xl text-zinc-700">Click, or Drag and drop image here.</div>
        <div class="text-base text-gray-400 mb-8">Supports the following formats: PNG, JPEG, WEBP, GIF.</div>
      </div>
      <div v-else>
        <div class="flex items-center gap-4 mb-1 bg-zinc-50 py-2 px-2 rounded-md" v-for="(file,i) in files">
          <a class="flex-1 " href="javascript:" @click="openHandle(file.file_name)">{{ file.file_name }}</a>
          <div class="flex items-center justify-center gap-2 shrink-0 w-[200px]" v-if="file.status.length > 0">
            <span class="capitalize" :class="{
              'text-green-500':file.status=='done',
              'text-red-500': file.status=='error',
              }">{{ file.status }}</span>
          </div>
          <div class="flex items-center justify-center gap-2 shrink-0 w-[200px]"
               v-if="file.status.length===0 && loading === false">
            <span class="">Convert to</span>
            <Select v-model="file.to_format">
              <SelectTrigger class="w-[80px]">
                <SelectValue placeholder="..."/>
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  <SelectItem value="jpeg">
                    JPEG
                  </SelectItem>
                  <SelectItem value="png">
                    PNG
                  </SelectItem>
                  <SelectItem value="webp">
                    WEBP
                  </SelectItem>
                </SelectGroup>
              </SelectContent>
            </Select>
          </div>
          <div class="w-[64px]">
            <Button type="button" variant="link" @click="handleRemoveItem(i)">
              <CircleX/>
            </Button>
          </div>
        </div>
        <div class="fixed bottom-12 right-14 flex items-center shadow-2xl rounded-full ">
          <button type="button" variant="link" :disabled="loading || !allFilesSet" @click="handleConvert"
                  :class="{
                       'bg-zinc-300 hover:bg-zinc-300':!allFilesSet
                  }"
                  class="flex rounded-full text-white transition-all ease-in-out bg-zinc-700 hover:bg-zinc-900 p-4">
            <LoaderCircle class="w-8 h-8 animate-spin" v-if="loading"/>
            <Send v-else class="w-8 h-8"/>
          </button>
        </div>
      </div>
    </div>
  </main>
</template>

// app/converter/page.tsx
"use client";

import {
  Button,
  Chip,
  getKeyValue,
  Select,
  SelectItem,
  Table,
  TableBody,
  TableCell,
  TableColumn,
  TableHeader,
  TableRow,
  Tooltip,
} from "@heroui/react";
import { readFile } from "@tauri-apps/plugin-fs";
import { useEffect, useReducer, useState } from "react";
import {
  converterReducer,
  ConverterImageFile,
  ImageFormatKey,
} from "@/app/converter/reducer";
import { open } from "@tauri-apps/plugin-dialog";
import React from "react";
import {
  DeleteIcon,
  LoaderPinwheel,
  SendHorizontal,
  TicketX,
  Trash2,
} from "lucide-react";
import { convertBytes } from "../utils";
import { invoke } from "@tauri-apps/api/core";
import { getCurrentWebview } from "@tauri-apps/api/webview";
import { ChooseFile } from "@/components/chooseFile";

interface ConverterFileResponse {
  saved_path: string;
  size: number;
}

const statusColorMap = {
  ready: "default",
  converting: "primary",
  error: "danger",
  converted: "success",
};

const formats = [
  { key: "jpg", label: "JPEG" },
  { key: "png", label: "PNG" },
  { key: "webp", label: "WEBP" },
  {key: "avif", label: "AVIF"},
  {key: "gif", label: "GIF"},
  {key: "bmp", label: "BMP"},
  {key: "tiff", label: "TIFF"},
  {key: "exr", label: "EXR"},
  {key: "hdr", label: "HDR"},
];

export default function Converter() {
  const [files, dispatch] = useReducer(converterReducer, []);
  const [converterLoading, setConverterLoading] = useState(false);
  const [savePath, setSavePath] = useState("");
  const [allToFormat, setAllToFormat] = useState<ImageFormatKey>("jpg");

  async function selectFileHandle() {
    const selected = await open({
      multiple: true,
      filters: [
        {
          name: "Images",
          extensions: ["png", "jpg", "jpeg", "jpg", "bmp"],
        },
      ],
    });
    if (Array.isArray(selected)) {
      // user selected multiple files
      for (let file of selected) {
        // 获取文件的类型
        const ext: string = await invoke("get_file_type", {
          filePath: file,
        });

        dispatch({
          type: "added",
          payload: {
            file_name: file.split("/").pop() || "",
            raw_path: file,
            from_format: ext as ImageFormatKey,
            to_format: "jpg",
            save_path: "",
            status: "ready",
          },
        });
      }
    } else if (selected === null) {
      // user
    }
  }

  useEffect(() => {
    getCurrentWebview().onDragDropEvent((event) => {
      if (event.payload.type === "enter") {
        // 清空 files
        dispatch({
          type: "clear",
          payload: {
            file_name: "",
            raw_path: "",
            from_format: "jpg",
            to_format: "jpg",
            save_path: "",
            status: "ready",
          },
        });
      }
      if (event.payload.type === "drop") {
        for (let file of event.payload.paths) {
          readFile(file).then((fileData) => {
            // 获取文件的类型
            invoke("get_file_type", {
              filePath: file,
            }).then((ext) => {
              dispatch({
                type: "added",
                payload: {
                  file_name: file.split("/").pop() || "",
                  raw_path: file,
                  save_path: "",
                  from_format: ext as ImageFormatKey,
                  to_format: "jpg",
                  status: "ready",
                },
              });
            });
          });
        }
      }
    });
  }, []);

  async function selectSavePathHandle() {
    const path = await open({
      directory: true,
      multiple: false,
    });

    if (path === null) {
      return;
    }

    setSavePath(path);
  }
  async function convertFileHandle() {
    setConverterLoading(true);

    for (let file of files) {
      if (file.status === "converted") {
        continue;
      }
      try {
        let resp: ConverterFileResponse = await invoke("convert", {
          filePath: file.raw_path,
          toFormat: file.to_format,
          saveDir: savePath,
        });
        file.save_path = resp.saved_path;
        file.status = "converted";
        dispatch({
          type: "changed",
          payload: file,
        });
      } catch (e: any) {
        file.status = "error";
        dispatch({
          type: "changed",
          payload: file,
        });
      }
    }
    setConverterLoading(false);
  }

  const renderCell = React.useCallback(
    (file: ConverterImageFile, columnKey: any) => {
      const cellValue = getKeyValue(file, columnKey);
      const statusColor = (statusColorMap[file.status] ?? "default") as
        | "default"
        | "primary"
        | "danger"
        | "success"
        | "secondary"
        | "warning"
        | undefined;
      switch (columnKey) {
        case "status":
          return (
            <Chip
              className="capitalize"
              color={statusColor}
              size="sm"
              variant="flat"
            >
              {cellValue}
            </Chip>
          );
        case "actions": {
          return (
            <div className="relative flex items-center gap-2">
              <Tooltip color="danger" content="Delete user">
                <span className="text-lg text-danger cursor-pointer active:opacity-50">
                  <Trash2 className="w-5 h-5" />
                </span>
              </Tooltip>
            </div>
          );
        }
        case "from_format": {
          return <span className="uppercase line-through">{cellValue}</span>;
        }
        case "to_format": {
          return (
            <Chip color="warning" variant="flat" className="uppercase">
              {cellValue}
            </Chip>
          );
        }
        default:
          return cellValue;
      }
    },
    []
  );

  return (
    <div className="h-full relative w-full">
      {files.length > 0 ? (
        <div className="h-full">
          <div className="flex gap-2 items-center mb-2">
            {/* <div className="flex-1"></div> */}
            <Button
              size="sm"
              className="flex-1 text-left flex items-center justify-start"
              onPress={selectSavePathHandle}
            >
              <span>
                {savePath
                  ? `Save path: ${savePath}`
                  : "Please select save path"}
              </span>
            </Button>
            <Select
              size="sm"
              className="max-w-40"
              selectedKeys={[allToFormat]}
              onChange={(e) => {
                setAllToFormat(e.target.value as ImageFormatKey);
                dispatch({
                  type: "set_all_to_format",
                  payload: {
                    to_format: e.target.value as ImageFormatKey,
                    raw_path: "",
                    save_path: "",
                    file_name: "",
                    from_format: "jpg",
                    status: "ready",
                  },
                });
              }}
            >
              {formats.map((format) => (
                <SelectItem key={format.key}>{format.label}</SelectItem>
              ))}
            </Select>
            <Button
              size="sm"
              color="primary"
              className="shadow-2xl "
              onPress={convertFileHandle}
              disabled={converterLoading}
            >
              {converterLoading ? (
                <LoaderPinwheel className="w-5 h-5 animate-spin" />
              ) : (
                <SendHorizontal className="w-5 h-5" />
              )}
              <span>Go!</span>
            </Button>
            <Button
              size="sm"
              className="shadow-2xl "
              onPress={() => {
                dispatch({
                  type: "clear",
                  payload: {
                    file_name: "",
                    raw_path: "",
                    from_format: "jpg",
                    to_format: "jpg",
                    save_path: "",
                    status: "ready",
                  },
                });
              }}
            >
              <TicketX className="w-5 h-5" />
              <span>Clear</span>
            </Button>
          </div>
          <Table aria-label="Files">
            <TableHeader>
              <TableColumn key={"file_name"}>File({files.length})</TableColumn>
              <TableColumn width={"100"} key={"from_format"}>
                Before Format
              </TableColumn>
              <TableColumn width={"120"} key={"to_format"}>
                Final Format
              </TableColumn>
              <TableColumn width={"120"} key={"status"}>
                Status
              </TableColumn>
              <TableColumn width={"80"} key={"actions"}>
                Actions
              </TableColumn>
            </TableHeader>
            <TableBody>
              {files.map((file: ConverterImageFile) => (
                <TableRow key={file.file_name}>
                  {(columnKey) => (
                    <TableCell>{renderCell(file, columnKey)}</TableCell>
                  )}
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      ) : (
        <div className="h-full pb-4 px-4">
          <div className="h-full mt-2 p-14 bg-zinc-300/20 rounded-xl">
            <ChooseFile onSelectFile={selectFileHandle} />
          </div>
        </div>
      )}
    </div>
  );
}
